### ISSUE TITLE
Stopped updating?

### ISSUE THREAD

**Issue by twpol** [russss/nhs-covid19-app-data#1]
The last commit is https://github.com/russss/nhs-covid19-app-data/commit/c4329864b03c0697670a88886c50f48e2573cb5e, 3 days ago now

The GitHub Actions are still running, but I can see this error in the most recent one:

`remote: error: File nhs_covid19_app_data.db is 101.35 MB; this exceeds GitHub's file size limit of 100.00 MB`

Hopefully this can be fixed 👍

**Comment by russss** [comment]
Ah shit, well spotted. I'll likely have to move this off github.

**Comment by russss** [comment]
Output has now moved to `https://files.russss.dev/nhs_covid19_app_data.db`

I think we might have lost a couple of days of venue data though...
